// Copyright 2019-2023 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// This module is imported in build.rs, and in the crate only for its unit tests.

//! Helpers for the files `build.rs` generates or edits from the `mobile` configuration.

use crate::config::AssociatedDomain;

/// Escapes a value for an XML attribute delimited by `"`.
pub fn xml_escape(value: &str) -> String {
    let mut escaped = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '&' => escaped.push_str("&amp;"),
            '<' => escaped.push_str("&lt;"),
            '>' => escaped.push_str("&gt;"),
            '"' => escaped.push_str("&quot;"),
            '\'' => escaped.push_str("&apos;"),
            c => escaped.push(c),
        }
    }
    escaped
}

/// The custom (non http/https) schemes of a domain, the ones iOS registers in
/// `CFBundleURLTypes`.
#[allow(dead_code)] // only used on macOS hosts
pub fn custom_schemes(domain: &AssociatedDomain) -> Vec<&str> {
    domain
        .scheme
        .iter()
        .map(String::as_str)
        .filter(|scheme| *scheme != "https" && *scheme != "http")
        .collect()
}

#[cfg(target_os = "macos")]
pub mod apple {
    use super::*;

    const ASSOCIATED_DOMAINS: &str = "com.apple.developer.associated-domains";
    const URL_TYPES: &str = "CFBundleURLTypes";
    const URL_SCHEMES: &str = "CFBundleURLSchemes";
    const URL_NAME: &str = "CFBundleURLName";

    /// Replaces the `applinks:` entries of the associated domains entitlement with
    /// `app_link_hosts`, keeping every other entry (`webcredentials:`, `activitycontinuation:`,
    /// ...). The key is removed when it ends up empty.
    pub fn merge_associated_domains(entitlements: &mut plist::Dictionary, app_link_hosts: &[&str]) {
        let mut domains = entitlements
            .get(ASSOCIATED_DOMAINS)
            .and_then(plist::Value::as_array)
            .map(|domains| {
                domains
                    .iter()
                    .filter(|d| !d.as_string().is_some_and(|d| d.starts_with("applinks:")))
                    .cloned()
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();
        domains.extend(
            app_link_hosts
                .iter()
                .map(|host| plist::Value::from(format!("applinks:{host}"))),
        );

        if domains.is_empty() {
            entitlements.remove(ASSOCIATED_DOMAINS);
        } else {
            entitlements.insert(ASSOCIATED_DOMAINS.into(), domains.into());
        }
    }

    /// Whether a `CFBundleURLTypes` entry has the shape this plugin generates: only a
    /// `CFBundleURLSchemes` list and a `CFBundleURLName` that is one of those schemes (or
    /// `http`/`https`, which older versions used when listed first).
    fn is_generated_url_type(url_type: &plist::Value) -> bool {
        let Some(dict) = url_type.as_dictionary() else {
            return false;
        };
        if dict.len() != 2 {
            return false;
        }
        let (Some(name), Some(schemes)) = (
            dict.get(URL_NAME).and_then(plist::Value::as_string),
            dict.get(URL_SCHEMES).and_then(plist::Value::as_array),
        ) else {
            return false;
        };
        name == "http"
            || name == "https"
            || schemes
                .iter()
                .any(|scheme| scheme.as_string() == Some(name))
    }

    /// Replaces the `CFBundleURLTypes` entries generated by this plugin with the ones for
    /// `domains`, keeping entries added by the user or other SDKs. The key is removed when it
    /// ends up empty.
    pub fn merge_url_types(info_plist: &mut plist::Dictionary, domains: &[&AssociatedDomain]) {
        let mut url_types = info_plist
            .get(URL_TYPES)
            .and_then(plist::Value::as_array)
            .map(|url_types| {
                url_types
                    .iter()
                    .filter(|url_type| !is_generated_url_type(url_type))
                    .cloned()
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();

        url_types.extend(domains.iter().filter_map(|domain| {
            let schemes = custom_schemes(domain);
            // http(s) only domains have nothing to register here
            let name = *schemes.first()?;
            let mut dict = plist::Dictionary::new();
            dict.insert(
                URL_SCHEMES.into(),
                schemes
                    .iter()
                    .map(|s| plist::Value::from(s.to_string()))
                    .collect::<Vec<_>>()
                    .into(),
            );
            dict.insert(URL_NAME.into(), name.to_string().into());
            Some(plist::Value::Dictionary(dict))
        }));

        if url_types.is_empty() {
            info_plist.remove(URL_TYPES);
        } else {
            info_plist.insert(URL_TYPES.into(), url_types.into());
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn domain(json: &str) -> AssociatedDomain {
        serde_json::from_str(json).unwrap()
    }

    #[test]
    fn escapes_xml_attributes() {
        assert_eq!(xml_escape("/a.*b"), "/a.*b");
        assert_eq!(
            xml_escape(r#"/a?b=1&c="<d>"'"#),
            "/a?b=1&amp;c=&quot;&lt;d&gt;&quot;&apos;"
        );
    }

    #[test]
    fn custom_schemes_skip_web_schemes() {
        assert_eq!(
            custom_schemes(&domain(r#"{ "scheme": ["https", "myapp"] }"#)),
            ["myapp"]
        );
        assert!(custom_schemes(&domain(r#"{ "scheme": [] }"#)).is_empty());
        assert!(custom_schemes(&domain(r#"{ "host": "a.b" }"#)).is_empty());
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn merges_associated_domains() {
        let mut entitlements = plist::Dictionary::new();
        entitlements.insert(
            "com.apple.developer.associated-domains".into(),
            vec![
                plist::Value::from("applinks:old.com"),
                plist::Value::from("webcredentials:example.com"),
            ]
            .into(),
        );

        apple::merge_associated_domains(&mut entitlements, &["new.com"]);
        assert_eq!(
            entitlements
                .get("com.apple.developer.associated-domains")
                .unwrap()
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_string().unwrap())
                .collect::<Vec<_>>(),
            ["webcredentials:example.com", "applinks:new.com"]
        );

        apple::merge_associated_domains(&mut entitlements, &[]);
        assert_eq!(
            entitlements
                .get("com.apple.developer.associated-domains")
                .unwrap()
                .as_array()
                .unwrap()
                .len(),
            1
        );

        let mut empty = plist::Dictionary::new();
        apple::merge_associated_domains(&mut empty, &[]);
        assert!(empty.is_empty());
    }

    #[cfg(target_os = "macos")]
    #[test]
    fn merges_url_types() {
        fn url_type(name: Option<&str>, schemes: &[&str], role: Option<&str>) -> plist::Value {
            let mut dict = plist::Dictionary::new();
            dict.insert(
                "CFBundleURLSchemes".into(),
                schemes
                    .iter()
                    .map(|s| plist::Value::from(s.to_string()))
                    .collect::<Vec<_>>()
                    .into(),
            );
            if let Some(name) = name {
                dict.insert("CFBundleURLName".into(), name.to_string().into());
            }
            if let Some(role) = role {
                dict.insert("CFBundleTypeRole".into(), role.to_string().into());
            }
            plist::Value::Dictionary(dict)
        }

        let google = url_type(None, &["com.googleusercontent.apps.123"], None);
        let xcode = url_type(Some("com.example.app"), &["fb123"], Some("Editor"));
        let mut info_plist = plist::Dictionary::new();
        info_plist.insert(
            "CFBundleURLTypes".into(),
            vec![
                google.clone(),
                // generated by an older version of the plugin
                url_type(Some("https"), &["oldscheme"], None),
                url_type(Some("stale"), &["stale"], None),
                xcode.clone(),
            ]
            .into(),
        );

        let custom =
            domain(r#"{ "scheme": ["https", "myapp", "other"], "appLink": false, "host": "a.b" }"#);
        let web_only = domain(r#"{ "scheme": ["https"], "appLink": false, "host": "a.b" }"#);
        let empty = domain(r#"{ "scheme": [] }"#);
        apple::merge_url_types(&mut info_plist, &[&custom, &web_only, &empty]);

        assert_eq!(
            info_plist.get("CFBundleURLTypes").unwrap(),
            &plist::Value::from(vec![
                google.clone(),
                xcode.clone(),
                url_type(Some("myapp"), &["myapp", "other"], None),
            ])
        );

        // running it again is stable
        let before = info_plist.clone();
        apple::merge_url_types(&mut info_plist, &[&custom]);
        assert_eq!(info_plist, before);

        apple::merge_url_types(&mut info_plist, &[]);
        assert_eq!(
            info_plist.get("CFBundleURLTypes").unwrap(),
            &plist::Value::from(vec![google, xcode])
        );

        let mut empty_plist = plist::Dictionary::new();
        apple::merge_url_types(&mut empty_plist, &[]);
        assert!(empty_plist.is_empty());
    }
}
