// Copyright 2019-2023 Tauri Programme within The Commons Conservancy
// SPDX-License-Identifier: Apache-2.0
// SPDX-License-Identifier: MIT

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async vibrate(duration: number): Promise<Result<null, Error>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('plugin:haptics|vibrate', { duration })
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async impactFeedback(
    style: ImpactFeedbackStyle
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('plugin:haptics|impact_feedback', { style })
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async notificationFeedback(
    type: NotificationFeedbackType
  ): Promise<Result<null, Error>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('plugin:haptics|notification_feedback', {
          type
        })
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async selectionFeedback(): Promise<Result<null, Error>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('plugin:haptics|selection_feedback')
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  }
}

/** user-defined types **/

/**
 * The error a command fails with: the message of the rejected IPC call, e.g. a missing
 * permission, invalid arguments or an error reported by the Android or iOS implementation.
 */
export type Error = string
/**
 * The style of an impact-feedback haptic.
 *
 * On iOS this maps directly to a `UIImpactFeedbackGenerator.FeedbackStyle` case. On Android,
 * which has no equivalent system API, each style instead plays a distinct vibration waveform of
 * increasing intensity. Has no effect on desktop platforms. Defaults to `Medium`.
 */
export type ImpactFeedbackStyle =
  | 'light'
  | 'medium'
  | 'heavy'
  | 'soft'
  | 'rigid'
/**
 * The type of notification feedback, indicating the outcome of a task or action.
 *
 * On iOS this maps directly to a `UINotificationFeedbackGenerator.FeedbackType` case. On
 * Android, which has no equivalent system API, each type instead plays a distinct vibration
 * waveform. Has no effect on desktop platforms. Defaults to `Success`.
 */
export type NotificationFeedbackType = 'success' | 'warning' | 'error'

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from '@tauri-apps/api/core'

export type Result<T, E> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E }
